### ISSUE TITLE
Removing images and containers

### ISSUE THREAD

**Issue by sstevens2** [dme26/docker-introduction#4]
I think it is important to teach them how to remove their containers, since these can often take up a lot of space on your machine.  I added some more detail in that section, since you can't remove an image if you have existing containers that reference that image.  You can see my additions [here](https://uw-madison-datascience.github.io/docker-introduction/05-creating-container-images/index.html).

Let me know what you think.

**Comment by sstevens2** [comment]
Related I also had them remove the image after they pushed to docker hub and then had them pull it back from docker hub.

**Comment by jduckles** [comment]
This has bit me several times on resource constrained machines so I agree!

**Comment by dme26** [comment]
- Regarding instructions for freeing up space, I absolutely agree these should be present, and weren't largely because I was rushing, and it was likely learners' machines would have been using Windows or macOS, wherein removing the Docker Desktop should also remove the VM the Docker Desktop uses, and all downloaded images with it.
- One implication in the immediately-upload-to-DockerHub approach—which I'm fine with, but it would be a change in design—is that we're teaching Docker + DockerHub. Originally I'd tried to sequence things to avoid that, mostly on the technical basis that a Docker ecosystem can be fully functional without the DockerHub. I guess I was thinking along the lines of the SWC git lesson, which doesn't involve GitHub until later episodes, as there's a similar git / GitHub separation. Of course for Docker to be useful, it's more likely to need a container image resource earlier. What do you reckon?

**Comment by sstevens2** [comment]
- I'll make a PR with my additions about removing images and containers so you can take a look.
- I really like the structure of docker first and then building to docker + dockerhub since it reduces the cognitive load and builds knowledge slowly like with the git lessons.  I think I was a little unclear though,  I teach them to remove early with `hello-world` but then have them remove and pull back down after they learn how to use dockerhub in the later part.  I think that part should still fit with what you are thinking about adding dockerhub later.  
- This is making me think we might want to think carefully about the beginning part a bit though.  I love the `hello-world` section but it does sneakily introduce docker hub prior to the section where we teach them dockerhub.

**Comment by sstevens2** [comment]
Added PR on expanding the section where we teach them to remove images and containers.

I'm thinking that maybe if we decide to include having them remove the image they push to github and then pull it back down we should include it as an exercise.

**Comment by dme26** [comment]
- Your PR is much appreciated @sstevens2 just working through it now.
- Using an exercise sounds like an ideal way to get the best of both worlds.
- I like that the removal instructions makes it clear that we haven't explicitly tested that removing Docker Desktop removes all images, although am noting to myself that this might sensibly sit as a separate issue (i.e., just testing the situation!).

**Comment by dme26** [comment]
New issue created regarding specific tests about whether removing Docker apps removes image cache over at  #13 so that this issue can be closed.
